<?php

/**
 * @file
 * Allows customized section titles.
 */

/**
 * Implements hook_menu().
 */
function gsb_custom_section_title_menu() {
  $items = array();
  $items['admin/config/gsb/custom-section-title'] = array(
    'title' => 'Custom Section Titles',
    'description' => 'Manage custom section titles',
    'page callback' => 'gsb_custom_section_title_overview',
    'access arguments' => array('administer custom section titles'),
    'file' => 'gsb_custom_section_title.admin.inc',
  );
  $items['gsb_custom_section_title/%ctools_js/delete/%/%'] = array(
    'page callback' => 'gsb_custom_section_title_delete_section',
    'page arguments' => array(3, 4, 1),
    'access arguments' => array('administer custom section titles'),
    'theme callback' => 'ajax_base_page_theme',
    'file' => 'gsb_custom_section_title.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function gsb_custom_section_title_permission() {
  return array(
    'administer custom section titles' => array(
      'title' => t('Administer custom section titles'),
    ),
  );
}

/**
 * Gets the custom section titles.
 *
 * @return array
 *   An array of custom section titles.
 */
function gsb_custom_section_title_get_sections() {
  return variable_get('gsb_custom_section_title_sections', array());
}

/**
 * Gets the custom section title for a given key.
 *
 * @param int|string $key
 *   The specific section.
 *
 * @return array
 *   An array representing the custom section title.
 */
function gsb_custom_section_title_get_section($key) {
  $sections = gsb_custom_section_title_get_sections();
  if (!isset($sections[$key])) {
    $sections[$key] = array(
      'title' => '',
      'link' => FALSE,
      'link_path' => '',
      'paths' => '',
    );
  }
  return $sections[$key];
}

/**
 * Sets the custom section titles.
 *
 * @param array $sections
 *   An array of custom section titles.
 */
function gsb_custom_section_title_set_sections(array $sections) {
  $sections = array_values($sections);
  foreach ($sections as $key => $section) {
    $section['id'] = $key;
  }
  variable_set('gsb_custom_section_title_sections', $sections);
}

/**
 * Implements hook_theme().
 */
function gsb_custom_section_title_theme() {
  return array(
    'gsb_custom_section_title_table' => array(
      'render element' => 'form',
    ),
  );
}
