<?php

/**
 * @file
 * Allows customized section titles.
 */

/**
 * Implements hook_menu().
 */
function gsb_custom_section_title_menu() {
  $items = array();
  $items['admin/config/user-interface/gsb-custom-section-title'] = array(
    'title' => 'GSB Custom Section Titles',
    'description' => 'Manage custom section titles',
    'page callback' => 'gsb_custom_section_title_overview',
    // @todo.
    'access callback' => TRUE,
    'file' => 'gsb_custom_section_title.admin.inc',
  );
  $items['gsb_custom_section_title/%ctools_js/delete/%'] = array(
    'page callback' => 'gsb_custom_section_title_delete_section',
    'page arguments' => array(3, 1),
    // @todo.
    'access callback' => TRUE,
    'theme callback' => 'ajax_base_page_theme',
    'file' => 'gsb_custom_section_title.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Gets the custom section titles.
 *
 * @param null $key
 *   (optional) If specified, returns the section title for a given key.
 *
 * @return array
 *   An array of custom section titles.
 */
function gsb_custom_section_title_get_sections($key = NULL) {
  $data = variable_get('gsb_custom_section_title_sections', array());
  if ($key !== NULL) {
    if (!isset($data[$key])) {
      $data[$key] = array(
        'title' => '',
        'link' => FALSE,
        'link_path' => '',
        'paths' => '',
      );
    }
    return $data[$key];
  }
  return $data;
}

/**
 * Sets the custom section titles.
 *
 * @param array $sections
 *   An array of custom section titles.
 */
function gsb_custom_section_title_set_sections(array $sections) {
  $sections = array_values($sections);
  foreach ($sections as $key => $section) {
    $section['id'] = $key;
  }
  variable_set('gsb_custom_section_title_sections', $sections);
}

/**
 * Implements hook_theme().
 */
function gsb_custom_section_title_theme() {
  return array(
    'gsb_custom_section_title_table' => array(
      'render element' => 'form',
    ),
  );
}
